wutsi:
  application:
    gateway-url: https://wutsi-gateway-test.herokuapp.com
    server-url: ${wutsi.application.gateway-url}/cash
  platform:
    cache:
      type: memcached
      memcached:
        username: ${MEMCACHIER_USERNAME}
        password: ${MEMCACHIER_PASSWORD}
        servers: ${MEMCACHIER_SERVERS}
    stream:
      type: rabbitmq
      rabbitmq:
        url: ${CLOUDAMQP_URL}
